
export const wordData = [
    { "text": "Multimedia", "value": 58},
    { "text": "Nanotechnology", "value": 91},
    { "text": "Combinatorics", "value": 90},
    { "text": "Algorithm", "value": 325},
    { "text": "Pathology", "value": 267},
    { "text": "Chemistry", "value": 667},
    { "text": "Social science", "value": 93},
    { "text": "Software system", "value": 178},
    { "text": "Information retrieval", "value": 149},
    { "text": "Distributed computing", "value": 127},
    { "text": "Genetics", "value": 532},
    { "text": "Data mining", "value": 221},
    { "text": "Parallel computing", "value": 70},
    { "text": "Suite", "value": 53},
    { "text": "Computer security", "value": 361},
    { "text": "Computer vision", "value": 102},
    { "text": "Art", "value": 151},
    { "text": "Theoretical computer science", "value": 201},
    { "text": "Cloud computing", "value": 76},
    { "text": "Biochemistry", "value": 569},
    { "text": "Political science", "value": 870},
    { "text": "Geology", "value": 527},
    { "text": "Composite material", "value": 190},
    { "text": "Chemical engineering", "value": 121},
    { "text": "Thermodynamics", "value": 240},
    { "text": "Psychiatry", "value": 125},
    { "text": "Data science", "value": 155},
    { "text": "Natural language processing", "value": 107},
    { "text": "Embedded system", "value": 77},
    { "text": "Medicine", "value": 804},
    { "text": "Mathematics", "value": 1632},
    { "text": "Metallurgy", "value": 90},
    { "text": "Cell biology", "value": 98},
    { "text": "World Wide Web", "value": 488},
    { "text": "Archaeology", "value": 306},
    { "text": "Marketing", "value": 99},
    { "text": "Operating system", "value": 1425},
    { "text": "Ecology", "value": 404},
    { "text": "History", "value": 410},
    { "text": "Internal medicine", "value": 422},
    { "text": "Neuroscience", "value": 101},
    { "text": "Epistemology", "value": 400},
    { "text": "Sociology", "value": 292},
    { "text": "Paleontology", "value": 208},
    { "text": "Quantum mechanics", "value": 815},
    { "text": "Geography", "value": 614},
    { "text": "Organic chemistry", "value": 377},
    { "text": "Software", "value": 779},
    { "text": "Finance", "value": 56},
    { "text": "Botany", "value": 99},
    { "text": "Internet privacy", "value": 51},
    { "text": "Mathematics education", "value": 62},
    { "text": "Linguistics", "value": 370},
    { "text": "Software quality", "value": 80},
    { "text": "Philosophy", "value": 987},
    { "text": "Software engineering", "value": 768},
    { "text": "Social psychology", "value": 85},
    { "text": "Discrete mathematics", "value": 99},
    { "text": "Process (computing)", "value": 125},
    { "text": "Pedagogy", "value": 66},
    { "text": "Law", "value": 697},
    { "text": "Systems engineering", "value": 134},
    { "text": "Electrical engineering", "value": 172},
    { "text": "Psychology", "value": 743},
    { "text": "Materials science", "value": 364},
    { "text": "Visual arts", "value": 51},
    { "text": "Biology", "value": 1636},
    { "text": "Economics", "value": 882},
    { "text": "Endocrinology", "value": 109},
    { "text": "Database", "value": 192},
    { "text": "Code (set theory)", "value": 170},
    { "text": "Computer science", "value": 1889},
    { "text": "Physical chemistry", "value": 66},
    { "text": "Mechanical engineering", "value": 211},
    { "text": "Immunology", "value": 113},
    { "text": "Source code", "value": 113},
    { "text": "Statistics", "value": 652},
    { "text": "Process management", "value": 81},
    { "text": "Mathematical analysis", "value": 96},
    { "text": "Set (abstract data type)", "value": 297},
    { "text": "Business", "value": 429},
    { "text": "Surgery", "value": 95},
    { "text": "Optoelectronics", "value": 55},
    { "text": "Human–computer interaction", "value": 186},
    { "text": "Engineering management", "value": 59},
    { "text": "Geometry", "value": 169},
    { "text": "Cancer", "value": 58},
    { "text": "Anthropology", "value": 63},
    { "text": "Nuclear magnetic resonance", "value": 69},
    { "text": "Optics", "value": 168},
    { "text": "Mathematical optimization", "value": 54},
    { "text": "Java", "value": 60},
    { "text": "Physics", "value": 1325},
    { "text": "Machine learning", "value": 458},
    { "text": "Artificial intelligence", "value": 1001},
    { "text": "Telecommunications", "value": 131},
    { "text": "Programming language", "value": 1365},
    { "text": "Software construction", "value": 98},
    { "text": "Computer network", "value": 234},
    { "text": "Gene", "value": 262},
    { "text": "Economic growth", "value": 63},
    { "text": "Software development", "value": 324},
    { "text": "Engineering", "value": 1724},
    { "text": "Knowledge management", "value": 170},
    { "text": "Management", "value": 308}
    ]